#!/usr/bin/env python3
"""
YouTube Cookies 导出工具
使用 browser_cookie3 库从浏览器读取 YouTube cookies 并导出为 yt-dlp 可用的格式
"""

import sys
import os

try:
    import browser_cookie3
except ImportError:
    print("❌ 缺少依赖库")
    print("\n请先安装 browser_cookie3：")
    print("  pip install browser_cookie3")
    sys.exit(1)


def get_youtube_cookies(browser_name='chrome'):
    """
    从浏览器获取 YouTube cookies

    支持的浏览器:
    - chrome (Chrome, Edge, Brave, Opera)
    - firefox
    - safari (仅 macOS)
    """

    browser_name = browser_name.lower()

    # 获取 cookies
    try:
        if browser_name == 'chrome':
            cookies = browser_cookie3.chrome(domain_name='.youtube.com')
            print(f"✅ 已从 Chrome 读取 cookies")
        elif browser_name == 'firefox':
            cookies = browser_cookie3.firefox(domain_name='.youtube.com')
            print(f"✅ 已从 Firefox 读取 cookies")
        elif browser_name == 'safari':
            cookies = browser_cookie3.safari(domain_name='.youtube.com')
            print(f"✅ 已从 Safari 读取 cookies")
        elif browser_name == 'edge':
            cookies = browser_cookie3.edge(domain_name='.youtube.com')
            print(f"✅ 已从 Edge 读取 cookies")
        elif browser_name == 'brave':
            cookies = browser_cookie3.brave(domain_name='.youtube.com')
            print(f"✅ 已从 Brave 读取 cookies")
        elif browser_name == 'opera':
            cookies = browser_cookie3.opera(domain_name='.youtube.com')
            print(f"✅ 已从 Opera 读取 cookies")
        else:
            print(f"❌ 不支持的浏览器: {browser_name}")
            print("\n支持的浏览器:")
            print("  chrome, firefox, safari, edge, brave, opera")
            sys.exit(1)
    except Exception as e:
        print(f"❌ 读取 cookies 失败: {e}")
        print("\n可能的原因:")
        print("  1. 浏览器未安装")
        print("  2. 浏览器正在运行（请先关闭浏览器）")
        print("  3. 浏览器数据被其他程序锁定")
        sys.exit(1)

    if not cookies:
        print("❌ 未找到 YouTube cookies")
        print("\n请确保:")
        print("  1. 你已经在浏览器中登录了 YouTube")
        print("  2. 访问过 https://www.youtube.com")
        sys.exit(1)

    return cookies


def export_cookies_netscape(cookies, output_file):
    """导出为 Netscape cookie 格式 (yt-dlp 格式)"""

    with open(output_file, 'w', encoding='utf-8') as f:
        # 写入文件头
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by Fish Music Cookie Exporter\n")
        f.write(f"# YouTube cookies for yt-dlp\n\n")

        count = 0
        for cookie in cookies:
            # 只写入 YouTube 相关的 cookies
            if 'youtube' in cookie.domain:
                # Netscape 格式: domain \t flag \t path \t secure \t expiration \t name \t value
                line = (
                    f"{cookie.domain}\t"
                    f"{'TRUE' if cookie.domain.startswith('.') else 'FALSE'}\t"
                    f"{cookie.path or '/'}\t"
                    f"{'TRUE' if cookie.secure else 'FALSE'}\t"
                    f"{int(cookie.expires) if cookie.expires else 0}\t"
                    f"{cookie.name}\t"
                    f"{cookie.value or ''}\n"
                )
                f.write(line)
                count += 1

    print(f"✅ 已导出 {count} 个 cookies 到 {output_file}")
    print(f"\n📁 文件大小: {os.path.getsize(output_file)} 字节")

    return count


def main():
    print("=" * 60)
    print("🍪 YouTube Cookies 导出工具")
    print("=" * 60)
    print()

    # 检测命令行参数
    if len(sys.argv) < 2:
        print("用法: python export-cookies.py <浏览器> [输出文件]")
        print()
        print("浏览器选项:")
        print("  chrome  - Google Chrome (默认)")
        print("  firefox - Mozilla Firefox")
        print("  edge    - Microsoft Edge")
        print("  safari  - Safari (仅 macOS)")
        print("  brave   - Brave Browser")
        print("  opera   - Opera")
        print()
        print("示例:")
        print("  python export-cookies.py chrome")
        print("  python export-cookies.py firefox /path/to/youtube-cookies.txt")
        print()
        sys.exit(1)

    browser_name = sys.argv[1]

    # 默认输出文件名
    output_file = 'youtube-cookies.txt'
    if len(sys.argv) >= 3:
        output_file = sys.argv[2]

    print(f"📋 步骤 1: 从 {browser_name} 读取 cookies")
    print()

    # 获取 cookies
    cookies = get_youtube_cookies(browser_name)

    print()
    print(f"📋 步骤 2: 导出为 Netscape 格式")
    print()

    # 导出 cookies
    count = export_cookies_netscape(cookies, output_file)

    print()
    print("=" * 60)
    print("✅ 导出完成！")
    print("=" * 60)
    print()
    print("📝 下一步操作:")
    print(f"1. 将 {output_file} 文件上传到服务器")
    print("2. 放在与 docker-compose.yml 相同的目录")
    print("3. 在 config.yaml 中配置: cookies_file: \"/app/youtube-cookies.txt\"")
    print("4. 重启服务: docker compose down && docker compose up -d")
    print()


if __name__ == '__main__':
    main()
